# Generated by Django 5.1.6 on 2025-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('passenger_type', models.CharField(choices=[('children', 'Children (0-10)'), ('adult', 'Adult'), ('old', 'Elder (50+)'), ('students', 'Students')], max_length=10)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_documents/')),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
    ]
