# Generated by Django 5.1.6 on 2025-02-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('Long Route', 'Long Routes (Night Bus)'), ('Short Route', 'Short Route (Local Bus)'), ('Reservations', 'Small (Reservation) Vehicle)')], max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
