# Generated by Django 5.1.6 on 2025-02-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_companyregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='passenger_capacity',
            field=models.CharField(default=35, max_length=15),
            preserve_default=False,
        ),
    ]
