# Generated by Django 5.1.6 on 2025-02-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_companyregistration_passenger_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('passenger_capacity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='vehicle_type',
            field=models.CharField(choices=[('Long Route', 'Long Routes (Night Bus)'), ('Short Route', 'Short Route (Local Bus)'), ('Reservations', 'Small (Reservation) Vehicle')], max_length=20),
        ),
    ]
