# Generated by Django 5.1.6 on 2025-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20250214_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='passenger_capacity',
            field=models.IntegerField(),
        ),
    ]
