# Generated by Django 5.1.6 on 2025-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_companyregistration_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('passenger_capacity', models.IntegerField()),
            ],
        ),
    ]
