# Generated by Django 5.1.6 on 2025-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticket', '0009_busroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_registration_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_registration_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='destination',
            field=models.CharField(choices=[('acham', 'Acham'), ('arghakhanchi', 'Arghakhanchi'), ('baglung', 'Baglung'), ('bajhang', 'Bajhang')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='origin',
            field=models.CharField(choices=[('acham', 'Acham'), ('arghakhanchi', 'Arghakhanchi'), ('baglung', 'Baglung'), ('bajhang', 'Bajhang')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
