# Generated by Django 5.1.6 on 2025-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_userregistration_groups_userregistration_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
