# Generated by Django 5.1.6 on 2025-04-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_companyregistration_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='comp_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('total_seats', models.PositiveIntegerField(default=30)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='ticket.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(default='Unknown Company', max_length=255)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.bus')),
            ],
            options={
                'ordering': ['-booking_time'],
                'constraints': [models.UniqueConstraint(fields=('bus', 'seat_number', 'departure_time'), name='unique_seat_per_bus_per_time')],
            },
        ),
    ]
