# Generated by Django 5.1.6 on 2025-04-17 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_busroute_comp_name_bus_bookedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
