# Generated by Django 5.1.6 on 2025-04-18 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 14, 50, 2, 770469, tzinfo=datetime.timezone.utc)),
        ),
    ]
