# Generated by Django 5.1.6 on 2025-04-29 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedticket',
            options={'verbose_name': 'Booked Ticket', 'verbose_name_plural': 'Booked Tickets'},
        ),
        migrations.RemoveConstraint(
            model_name='bookedticket',
            name='unique_seat_per_bus_per_time',
        ),
        migrations.RenameField(
            model_name='bookedticket',
            old_name='passenger_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookedticket',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='bookedticket',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='bookedticket',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='bookedticket',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='bookedticket',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='payment',
            field=models.CharField(choices=[('Cash on counter', 'Cash on counter'), ('online payment', 'online payment')], default='Cash on Counter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='paymentproof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='departure_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='email',
            field=models.EmailField(default='unknown@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 14, 45, 39, 675073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='bookedticket',
            table='ticket_bookedticket',
        ),
    ]
