# Generated by Django 5.1.6 on 2025-04-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_alter_bookedticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedticket',
            options={},
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='vech_no',
            field=models.CharField(default=2035, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='paymentproof',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 16, 11, 3, 611209, tzinfo=datetime.timezone.utc)),
        ),
    ]
