# Generated by Django 5.1.6 on 2025-04-29 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_bookedticket_options_bookedticket_vech_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 16, 16, 14, 389516, tzinfo=datetime.timezone.utc)),
        ),
    ]
