# Generated by Django 5.1.6 on 2025-04-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 16, 48, 6, 902097, tzinfo=datetime.timezone.utc)),
        ),
    ]
