# Generated by Django 5.1.6 on 2025-04-30 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='Seat_no',
            field=models.CharField(default='c4', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='Ticket_no',
            field=models.CharField(default='tkt-2555', editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 14, 20, 30, 106612, tzinfo=datetime.timezone.utc)),
        ),
    ]
