# Generated by Django 5.1.6 on 2025-04-30 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_bookedticket_seat_no_bookedticket_ticket_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 14, 21, 5, 133060, tzinfo=datetime.timezone.utc)),
        ),
    ]
