# Generated by Django 5.1.6 on 2025-05-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 10, 17, 12, 217633, tzinfo=datetime.timezone.utc)),
        ),
    ]
