# Generated by Django 5.1.6 on 2025-05-16 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='price',
            field=models.IntegerField(default=30, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 46, 13, 362230, tzinfo=datetime.timezone.utc)),
        ),
    ]
