# Generated by Django 5.1.6 on 2025-05-16 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_busroute_price_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 49, 28, 336638, tzinfo=datetime.timezone.utc)),
        ),
    ]
