# Generated by Django 5.1.6 on 2025-05-16 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_alter_busroute_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 56, 9, 411975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
